remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins

title: [Welcome to __ WorldğŸŒ]
description: [Hello This is dstyaaaaaa~ğŸ§šâ€â™‚ï¸Write sth randomly.]
